name: Deploy Lambda Function

on:
  push:
    branches: [pipeline]

env:
  AWS_REGION: eu-north-1
  LAMBDA_FUNCTION_NAME: KinesisIngestion

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Prepare Lambda Build Directory
      run: |
        cd data-processing/lambda_functions
        mkdir -p build
        # Only install what's needed (excluding pandas)
        pip install -r ../../requirements.txt -t build
        cp lambda_processor.py build/

    - name: Zip Lambda Function
      run: |
        cd data-processing/lambda_functions/build
        zip -r ../../lambda.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://data-processing/lambda.zip
